# Generated by Django 5.0.1 on 2024-01-24 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='bio',
        ),
    ]
