# Generated by Django 5.0.1 on 2024-01-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_remove_user_bio_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transactions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawn_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
