# Generated by Django 5.0.1 on 2024-01-31 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_remove_user_balance_deposit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deposit',
        ),
    ]
